apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - target:
      kind: Deployment
      name: keikenchi-map
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Ingress
      name: keikenchi-map
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.keikenchi-map.example.com

images:
  - name: keikenchi-map
    newName: ghcr.io/yude/swarm-keikenchi
    newTag: main
