apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: keikenchi-map
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  - target:
      kind: Ingress
      name: keikenchi-map
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: keikenchi-map.example.com

images:
  - name: keikenchi-map
    newName: ghcr.io/yude/swarm-keikenchi
    newTag: latest
