apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keikenchi-map
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: keikenchi-map.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keikenchi-map
                port:
                  number: 80
